zero-patients/Pandemic

client/components/Board.js
client/components/CityMarker.js

cities mapped to board closes #32, closes #15

---

client/data/infectionDeck.js
package.json
script/seedFirebase.js

Seed file for Firebase. Contains cities, and infection deck at the moment.

Seed file for Firebase closes #34

---

client/app.js
client/data/infectionDeck.js
client/funcs/utils.js

added main shuffle funcs for player and epidemic decks

---

client/components/Board.js
client/data/cities.js

lines added to connect cities

---

client/components/Controller.js
public/style.css

created a flexbox controller view. Most likely will have to be broken down into more react components, but the styling is there. I included the hardcoded functions in the bottom for buttons from the right in order to demonstrate that we can still controll the players.

Controller styling /#40

---

client/components/Controller.js
client/components/PlayerPawn.js
client/data/cities.js
client/data/playerInfo.js
script/seedFirebase.js

Player movement to cities closes #57

---

client/components/InfectionCard.js
client/funcs/utils.js

updated shuffle funcs to not delete connections

---

client/components/Board.js
client/components/CityMarker.js
client/components/EpidemicTracker.js
client/data/cities.js
public/style.css

Some map fixes and start of epidemic tracker

started epidemic tracker

---

client/components/Controller.js

Player movement to cities #57

---

client/components/Board.js
client/components/StatusBar.js
public/index.html

status bar done closes #102 closes #104 closes #106

---

client/data/infectionStatus.js
script/seedFirebase.js

Added infectionStatus object to Firestore and created seed file to create intitial values

---

client/components/Board.js
client/components/InfectionCardsContainer.js
client/routes.js
package-lock.json
package.json
public/index.html

fix: Created InfectionCardsContainer component to house infection card deck, and discard pile

---

client/funcs/isWinLoss.js

all win loss functions written. need to be moved to respective components

feature: win condition added, checking cured diseases

---

client/components/Controller/Footer.js
client/components/Controller/Header.js
client/components/Controller/MainView.js

feature: Infection card button now adds infection to the city selected from the deck

---

client/components/Controller/MainView.js

feature: Adding infections to the board updates the count in the status bar

---

client/components/Board.js
client/components/CityMarker.js
client/components/Controller/Header.js
client/components/Controller/MainView.js
client/components/InfectionDeck.js
client/components/InfectionDiscardDeck.js
client/components/InfectionRate.js
client/components/OutbreakTracker.js
client/components/PlayerDeck.js
client/components/PlayerDiscardDeck.js
client/components/PlayerPawn.js
client/components/StatusBar.js
client/funcs/isWinLoss.js
client/funcs/utils.js
script/seedFirebase.js

closes #144 
Replaced all instances of the string "'YzQ0qR6LZ7gxd8E03k1l'" with the constant CURRENT_GAME imported from secrets.js (there could be a better place for this, but it seemed the best candidate at th time)
this should allow us to create and test separate instances of the DB by replacing only one line of code in each branch we make.

144 make game room a constant

---

.gitignore
client/components/Controller/MainView.js
client/funcs/utils.js
secrets.js

feature: adding a cdc to the board now decrements the player action count. We need to pass the current player id down to every component that makes an action function call in order to full implement  game state changes.

155 update functions to modify player action counter

---

client/components/Controller/Header.js
client/components/Controller/MainView.js
client/components/Controller/MoveView.js
client/components/Controller/airplaneMoves.js
secrets.js

updated discard for direct flights and updated header info to display correct info

169 discard a card when you fly

---

client/components/Controller/MainView.js
client/components/Controller/PlayerCard.js
client/components/Controller/PlayerHand.js
public/style.css
secrets.js

closes #173 
player cards now render with a background color that matches their "region" and "disease color"

player cards now render with their color as a background

---

client/components/Controller/MainView.js

closes #95
closes #98
closes #99

feature: Implemented logic for triggering an epidemic when the epidemic card is drawn

---

client/components/Controller/Footer.js
client/components/Controller/MainView.js
client/components/Controller/PlayerHand.js
client/components/Controller/TreatView.js
script/seedFirebase.js

closes #117 turn logic implemented

Player turns

---

client/components/Controller/Footer.js

fix: Removed "Infect" button from the controller

---

client/components/Controller/MainView.js

fix: bug#186 - drawing an infection card now infects the city

---

client/data/infectionDeck.js
client/data/playerDeck.js
script/seedFirebase.js

added infections at start of game

feature: infection cards are drawn at start of game initialization

---

client/components/Board.js
client/components/CityMarker.js
client/components/Infection.js
client/components/ResearchStation.js
client/data/cities.js
client/data/playerInfo.js
public/style.css

increased size of board components
